### ISSUE TITLE
Decide finished goals

### ISSUE THREAD

**Issue by Crothos** [Crothos/financial-planner#48]

**Comment by chefkeii** [comment]
Acceptance Criteria

1. [ ] It's done when the / homepage route renders a list of all projects from the database.

2. [ ] It's done when the /project/:id route renders an individual project's details based on the route parameter id.

3. [ ] It's done when the /login route renders a form to log in and a form to create a new account.

4. [ ] It's done when an existing user can enter their credentials on the login page to create a session on the server.

5. [ ] It's done when a new user can create an account on the login page and then be immediately logged in with a session.

6. [ ] It's done when the /profile route renders the logged-in user's projects and a form to create a new project.

7. [ ] It's done when only a logged in user can visit the /profile route.

8. [ ] It's done when a logged in user is redirected to /profile when they try to visit /login again.

9. [ ] It's done when a user on the profile page can use the form to create a new project in the database.

10. [ ] It's done when a user on the profile page can select a "Delete" button to remove their project from the database.

11. [ ] It's done when a logged-in user can select a "Logout" button to remove their session.

12. [ ] It's done when the session for a logged-in user expires after a set time.

13. [ ] It's done when the API routes to create and delete posts are protected from non logged-in users.

14. [ ] It's done when the code is organized using MVC architecture.

15. [ ] It's done when the views are rendered with Handlebars.js templates.
